site_name: hazzy
site_description: A Touchscreen UI for LinuxCNC
site_url: https://kurtjacobson.github.io/hazzy/

repo_name: KurtJacobson/hazzy
repo_url: https://github.com/KurtJacobson/hazzy/

site_author: Kurt Jacobson
copyright: Copyright &copy; 2017  Kurt Jacobson

theme: material


pages:
- Home: index.md
- Installing: installing.md
- Utilities:
  - Status Monitor: utilities/status_monitor.md


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false, linenums=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde


extra:
  palette:
    primary: Grey
    accent: Grey
